In [160]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import accuracy_score
import sklearn
from sklearn.metrics import confusion_matrix
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.feature_selection import VarianceThreshold
from sklearn.naive_bayes import GaussianNB
from sklearn.feature_selection import GenericUnivariateSelect

from sklearn import tree
from sklearn import preprocessing
from sklearn import metrics
from sklearn import model_selection

from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold
from sklearn.metrics import accuracy_score 

import graphviz
from sklearn.ensemble import RandomForestClassifier

In [161]:
def preprocessData(data):
    data = data.replace('Unknown', np.nan)
    data.dropna(inplace=True)
    
    le = preprocessing.LabelEncoder()
    for column_name in data.columns:
        if data[column_name].dtype == object:
            data[column_name] = le.fit_transform(data[column_name])
        else:
            pass
    
    return data

In [162]:
propertyData = pd.read_csv("property_prices.csv")

propertyData['lowBand'], propertyData['highBand'] = propertyData['price_bands'].str.split('-', 1).str
propertyData['lowBand'] = propertyData['lowBand'].str[:-1]
propertyData['highBand'] = propertyData['highBand'].str[:-1]

propertyData = preprocessData(propertyData)

In [163]:
droppedColumns = ['id','lowBand','highBand','price_bands','date','car_parks','bathrooms','address', 'suburb', 'suburb_property_count',
                              'council_area', 'method']
attribute = ['rooms', 'type', 'realestate_agent', 'distance', 'postcode', 'bedrooms', 'landsize', 'building_area', 'year_built', 'lattitude', 'longtitude', 'region_name']
Y = propertyData['lowBand']
X = propertyData.drop(columns=droppedColumns)

In [164]:
X = pd.get_dummies(X)

num_trees = 500
max_features = 3
kfold = model_selection.KFold(n_splits=10, random_state=0)

In [165]:
forest_reg = RandomForestClassifier(n_estimators=num_trees, random_state=0) 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2) 
forest_reg.fit(X_train, y_train) 
print(forest_reg.score(X_train,y_train)) 
results = model_selection.cross_val_score(forest_reg, X_train, y_train, cv=kfold) 
print(results.mean())
cnf_matrix = confusion_matrix(y_train, forest_reg.predict(X_train))
print(cnf_matrix)

0.9998593332395554
0.6920823676234623
[[   4    0    0    0    0    0    0]
 [   0 2420    0    0    0    0    0]
 [   0    0  626    0    0    0    0]
 [   0    0    0  271    1    0    0]
 [   0    0    0    0 1126    0    0]
 [   0    0    0    0    0 1484    0]
 [   0    0    0    0    0    0 1177]]
